# Generated by Django 4.1.13 on 2023-11-23 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0002_contact"),
    ]

    operations = [
        migrations.CreateModel(
            name="EmailContact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=50)),
                ("empresa", models.CharField(max_length=50)),
                ("correo", models.EmailField(max_length=254)),
                ("mensaje", models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name="Contact",
        ),
    ]
